### ISSUE TITLE
error: command 'gcc' failed with exit status 1

### ISSUE THREAD

**Issue by minygd** [meder411/Spherical-Package#1]
Hi, I meet an Error while building the Extension in a Server with Titan RTX and OS Ubuntu 18.04(gcc/g++ 5.5.0) machine. My Pytorch vision is 1.0.0 and all dependencies are well prepared.

A lot of message are presented as:
```
   T *grad_input_ptr           = grad_input.data_ptr<T>();

../Spherical-Package/ext_modules/include/cpp/mapped_avg_pool.h:98:56: error:expected primary-expression before ‘)’ token
 ```
So I think the reference code are in [this link](https://github.com/meder411/Spherical-Package/blob/master/ext_modules/include/cpp/mapped_avg_pool.h#L98)

And the final report is: `error: command 'gcc' failed with exit status 1`

**Comment by meder411** [comment]
The issue is the pytorch version. I think it was around pytorch 1.3.0 when the C++ API changed for referencing a tensor’s pointer, which is what is now causing your error. Please update pytorch to the current stable version and this should go away.

**Comment by meder411** [comment]
I've updated the readme to show that this needs at least pytorch 1.4.0 or higher.

**Comment by minygd** [comment]
@meder411 Hi, thank you. After changing to Pytorch 1.5.1, the errors mentioned above have gone. But another error occurs:

```
../../Spherical-Package/ext_modules/include/core/distortion.h:144:67: error: no matching function for call to ‘host_device_max(double, int)’
                                          abs(rel_step_size * x(1)));
```

I search for function `host_device_max()`, and finally get it in [this link](https://github.com/meder411/Spherical-Package/blob/master/ext_modules/include/core/util.h#L46). So I have tried to paste it in `distortion.h`, but failed to build with the error and also a `note` below:(Since I paste it in `distortion.h`L#40 and build)

```
../../Spherical-Package/ext_modules/include/core/distortion.h:41:30: note: candidate: template<class T> T spherical::core::host_device_max(T, T)
 __host__ __device__ inline T host_device_max(const T val1, const T val2) {

```

**Comment by meder411** [comment]
Sorry for the delay. Let me take a look, and I'll see if I can replicate this.

**Comment by minygd** [comment]
It's fine, THX!

**Comment by minygd** [comment]
> Sorry for the delay. Let me take a look, and I'll see if I can replicate this.

Hi, I still can't implement the `Spherical-Package`, do you replicate it?

**Comment by meder411** [comment]
I just checked everything using the provided Docker setup. There actually was a typo with the Dockerfile, but this was a different error than you are running into. With the changes I just pushed (v.1.0.2), the Docker setup works correctly and all tests pass and examples run. 

If you are still running into this issue, I recommend either using the provided Docker setup or simply running the commands from the Dockerfile sequentially to manually install the dependencies.
